name: 🚀 Deploy to VM

on:
  push:
    branches:
      - main
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Virtual Machine
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔑 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            echo "🚀 Начинаем деплой на виртуальной машине..."
            
            # Переходим в папку проекта
            cd /opt/empalar-mall
            
            # Получаем последние изменения
            echo "📥 Получаем изменения из репозитория..."
            git pull origin main
            
            # Перезапускаем контейнеры
            echo "🔄 Перезапускаем Docker контейнеры..."
            sudo docker-compose down
            sudo docker-compose build --no-cache
            sudo docker-compose up -d
            
            echo "✅ Деплой завершен успешно!"
            
      - name: 📢 Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Deploy to VM
          SLACK_MESSAGE: 'Deploy to VM ${{ job.status }}' 