name: 🚀 Deploy to VM

on:
  push:
    branches:
      - master
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Virtual Machine
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        
      - name: 🔑 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            echo "🚀 Начинаем деплой на виртуальной машине..."
            
            # Переходим в папку проекта
            cd ${{ secrets.VM_PROJECT_PATH }}
            
            # Получаем последние изменения
            echo "📥 Получаем изменения из репозитория..."
            git pull origin master
            
            # Устанавливаем зависимости
            echo "📦 Устанавливаем зависимости..."
            npm install
            
            # Собираем фронтенд
            echo "🔨 Собираем фронтенд..."
            npm run build
            
            # Перезапускаем приложение
            echo "🔄 Перезапускаем приложение..."
            pm2 restart empalar-mall || pm2 start backend/index.js --name empalar-mall
            
            # Перезапускаем Nginx
            echo "🌐 Перезапускаем Nginx..."
            sudo systemctl reload nginx
            
            echo "✅ Деплой завершен успешно!"
            
      - name: 📢 Notification
        if: success()
        run: |
          echo "🎉 Деплой на виртуальную машину завершен успешно!"
          echo "🌐 Приложение доступно по адресу: https://${{ secrets.VM_HOST }}" 